# Generated by Django 4.1.7 on 2023-09-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('img', models.ImageField(upload_to="{% static 'content/images' %}")),
                ('time', models.CharField(max_length=255)),
                ('worning', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=20)),
                ('movie', models.FileField(upload_to="{% static 'content/movies' %}")),
                ('category', models.ManyToManyField(related_name='cate_movie', to='content.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
