# Generated by Django 4.1.7 on 2023-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='images/}'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(upload_to='movies/'),
        ),
    ]
