# Generated by Django 4.1.7 on 2023-09-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='abut',
            field=models.TextField(blank=True, null=True),
        ),
    ]
