# Generated by Django 4.2.1 on 2023-09-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_likeseryal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeseryal',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_seryal', to='content.seryalmovie'),
        ),
    ]
